name: build-images
on:
  push:
    branches:
      - main
    workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: chanwit
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: distroless/actions/apko-publish@main
        with:
          config: apko-0.10.0.yaml
          tag: ghcr.io/llm-gitops/images/apko:0.10.0

      - uses: distroless/actions/apko-publish@main
        with:
          config: postgres-15.4.yaml
          tag: ghcr.io/llm-gitops/images/postgres:15.4
